# Generated by Django 5.2.11 on 2026-02-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymentintent_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
