# Generated by Django 5.2.11 on 2026-02-27 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0003_alter_paymentintent_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
