# Generated by Django 5.2.11 on 2026-06-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_country_paymentgateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], default='created', max_length=30),
        ),
    ]
