
class ProvinceClass():
    
    def __init__(self, country):
        self.country=country
        
    def Iran():
        provinces=Iran = (
            ("AL", "Alborz"),
            ("AR", "Ardabil"),
            ("BS", "Bushehr"),
            ("CH", "Chaharmahal and Bakhtiari"),
            ("ES", "Isfahan"),
            ("FA", "Fars"),
            ("GO", "Gilan"),
            ("HG", "Hamedan"),
            ("HR", "Hormozgan"),
            ("IL", "Ilam"),
            ("KE", "Kerman"),
            ("KB", "Kohgiluyeh and Boyer-Ahmad"),
            ("KD", "Kurdistan"),
            ("KZ", "Khuzestan"),
            ("LK", "Lorestan"),
            ("MK", "Markazi"),
            ("MA", "Mazandaran"),
            ("NK", "North Khorasan"),
            ("QO", "Qom"),
            ("QA", "Qazvin"),
            ("RA", "Razavi Khorasan"),
            ("SE", "Semnan"),
            ("SB", "Sistan and Baluchestan"),
            ("SK", "South Khorasan"),
            ("TE", "Tehran"),
            ("WA", "West Azerbaijan"),
            ("YA", "Yazd"),
            ("ZN", "Zanjan")
        )

    
    def UnitedState():
        provinces=(
            ("AL", "Alabama"),
            ("AK", "Alaska"),
            ("AZ", "Arizona"),
            ("AR", "Arkansas"),
            ("CA", "California"),
            ("CO", "Colorado"),
            ("CT", "Connecticut"),
            ("DE", "Delaware"),
            ("FL", "Florida"),
            ("GA", "Georgia"),
            ("HI", "Hawaii"),
            ("ID", "Idaho"),
            ("IL", "Illinois"),
            ("IN", "Indiana"),
            ("IA", "Iowa"),
            ("KS", "Kansas"),
            ("KY", "Kentucky"),
            ("LA", "Louisiana"),
            ("ME", "Maine"),
            ("MD", "Maryland"),
            ("MA", "Massachusetts"),
            ("MI", "Michigan"),
            ("MN", "Minnesota"),
            ("MS", "Mississippi"),
            ("MO", "Missouri"),
            ("MT", "Montana"),
            ("NE", "Nebraska"),
            ("NV", "Nevada"),
            ("NH", "New Hampshire"),
            ("NJ", "New Jersey"),
            ("NM", "New Mexico"),
            ("NY", "New York"),
            ("NC", "North Carolina"),
            ("ND", "North Dakota"),
            ("OH", "Ohio"),
            ("OK", "Oklahoma"),
            ("OR", "Oregon"),
            ("PA", "Pennsylvania"),
            ("RI", "Rhode Island"),
            ("SC", "South Carolina"),
            ("SD", "South Dakota"),
            ("TN", "Tennessee"),
            ("TX", "Texas"),
            ("UT", "Utah"),
            ("VT", "Vermont"),
            ("VA", "Virginia"),
            ("WA", "Washington"),
            ("WV", "West Virginia"),
            ("WI", "Wisconsin"),
            ("WY", "Wyoming")
        )
