# Generated by Django 4.2.14 on 2024-08-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartpred', '0002_remove_heart_diabetes'),
    ]

    operations = [
        migrations.AddField(
            model_name='heart',
            name='diabetes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
