# Generated by Django 6.0.2 on 2026-02-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscriptionusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'فعال'), ('expired', 'منقضی'), ('canceled', 'لغو شده')], db_index=True, default='trial', max_length=20),
        ),
    ]
