# Generated by Django 5.2.11 on 2026-02-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_payment_payment_url_payment_verified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptioninvoice',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
