# Generated by Django 5.2.11 on 2026-02-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_remove_subscriptioninvoice_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioninvoice',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending Payment'), ('paid', 'Paid'), ('expired', 'Expired'), ('failed', 'Failed')], default='created', max_length=20),
        ),
    ]
