# Generated by Django 5.2.11 on 2026-02-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_subscriptioninvoice_payment_intent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptioninvoice',
            name='payment_intent',
        ),
    ]
