# Generated by Django 5.2.11 on 2026-02-27 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymentintent_object_id'),
        ('subscription', '0008_remove_subscriptioninvoice_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='payment_intent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_invoice', to='payments.paymentintent'),
        ),
    ]
