# Generated by Django 5.1.1 on 2025-11-09 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('products', '0003_store_markant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='zarinpal_ref_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد پیگیری زرین\u200cپال'),
        ),
        migrations.CreateModel(
            name='SplitPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ قابل پرداخت به فروشنده')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.store', verbose_name='فروشنده')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_payments', to='payment.transaction')),
            ],
            options={
                'verbose_name': 'تقسیم پرداخت',
                'verbose_name_plural': 'تقسیم\u200cهای پرداخت',
            },
        ),
    ]
