# Generated by Django 5.1.1 on 2025-12-16 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_transaction_zarinpal_ref_id_splitpayment'),
        ('products', '0004_productvariant_products_pr_product_cee51f_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart'], name='payment_car_cart_id_02ceaf_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['product'], name='payment_car_product_58a91c_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['variant'], name='payment_car_variant_800756_idx'),
        ),
    ]
