# Generated by Django 5.1.3 on 2025-02-10 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_transaction_user_transaction_profile'),
        ('products', '0016_remove_product_is_available_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sale Date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='products.product', verbose_name='Product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='products.store', verbose_name='Seller')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='payment.transaction', verbose_name='Transaction')),
            ],
        ),
    ]
