# Generated by Django 4.2.14 on 2024-08-27 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='Alex', max_length=100, null=True)),
                ('lname', models.CharField(default='Smith', max_length=150, null=True)),
                ('avatar', models.ImageField(default='', upload_to='registration/user_avatars')),
                ('birthday', models.DateTimeField()),
                ('Phone', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
