# Generated by Django 5.2.6 on 2025-10-07 10:53

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='server_store',
            field=models.ForeignKey(default=accounts.models.ProfileModel.get_default_store, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_profiles', to='products.store', verbose_name='Server Store'),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.profilemodel'),
        ),
    ]
