# Generated by Django 6.0.2 on 2026-02-20 16:37

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='store',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_address', to='products.store', verbose_name='Store'),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='server_store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_profiles', to='products.store', verbose_name='Server Store'),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.profilemodel', verbose_name='Profile'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['profile', 'shipping_is_active'], name='accounts_ad_profile_ba1744_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['store'], name='accounts_ad_store_i_2f2023_idx'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('profile__isnull', False), ('store__isnull', True)), models.Q(('profile__isnull', True), ('store__isnull', False)), _connector='OR'), name='address_owner_check'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.CheckConstraint(condition=models.Q(('profile__isnull', False), ('shipping_is_active', False), _connector='OR'), name='active_address_only_for_profiles'),
        ),
    ]
