# Generated by Django 5.1.1 on 2025-12-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='hidden_videos',
            field=models.JSONField(default=dict),
        ),
    ]
