# Generated by Django 5.2.6 on 2025-09-22 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profilemodel_lang'),
        ('products', '0005_alter_store_tel_channel_alter_store_tel_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='server_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_profiles', to='products.store', verbose_name='Server Store'),
        ),
    ]
