# Generated by Django 5.2.11 on 2026-05-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profilemodel_bale_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='bale',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Bale ID'),
        ),
    ]
