# Generated by Django 5.2.1 on 2025-05-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_special_user_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='shipping_country',
            field=models.CharField(max_length=50, verbose_name='Country'),
        ),
    ]
