# Generated by Django 5.1.1 on 2025-12-22 22:45

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profilemodel_hidden_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='store_menu',
            field=models.JSONField(blank=True, default=accounts.models.ProfileModel.default_store_menu),
        ),
    ]
