# Generated by Django 4.2.14 on 2024-08-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profilemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='background_pic',
            field=models.ImageField(default='', upload_to='registration/user_avatars'),
        ),
    ]
