# Generated by Django 5.2.6 on 2025-09-22 14:07

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profilemodel_server_store'),
        ('products', '0006_remove_store_profile_store_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='server_store',
            field=models.ForeignKey(default=accounts.models.ProfileModel.get_default_store, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_profiles', to='products.store', verbose_name='Server Store'),
        ),
    ]
