# Generated by Django 5.1.1 on 2025-12-24 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profilemodel_store_menu'),
        ('products', '0006_remove_store_city_remove_store_province'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AddField(
            model_name='address',
            name='store',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_address', to='products.store', verbose_name='Store'),
        ),
        migrations.AlterField(
            model_name='address',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.profilemodel', verbose_name='Profile'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['profile', 'shipping_is_active'], name='accounts_ad_profile_ba1744_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['store'], name='accounts_ad_store_i_2f2023_idx'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('profile__isnull', False), ('store__isnull', True)), models.Q(('profile__isnull', True), ('store__isnull', False)), _connector='OR'), name='address_owner_check', violation_error_message='آدرس باید یا متعلق به پروفایل باشد یا فروشگاه، نه هر دو'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('profile__isnull', False), ('shipping_is_active', True)), models.Q(('profile__isnull', False), ('shipping_is_active', False)), models.Q(('profile__isnull', True), ('shipping_is_active', False)), _connector='OR'), name='active_address_only_for_profiles', violation_error_message='آدرس فعال فقط برای پروفایل\u200cها معتبر است'),
        ),
    ]
