# Generated by Django 4.2.14 on 2024-08-28 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profilemodel_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='IranAddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=300, verbose_name='Address Line 1')),
                ('line2', models.CharField(max_length=300, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=10, verbose_name='City')),
                ('province', models.CharField(choices=[('WAZ', 'West Azerbaija'), ('EAZ', 'East Azerbaijan'), ('ARD', 'Ardabil'), ('KRD', 'Kurdistan'), ('ZAJ', 'Zanjan'), ('GIL', 'Gilan'), ('KRS', 'Kermanshah'), ('HAM', 'Hamadan'), ('QAZ', 'Qazvin'), ('ILM', 'Ilam'), ('LOR', 'Lorestan'), ('MRK', 'Markazi'), ('QOM', 'Qom'), ('THR', 'Tehra'), ('ALB', 'Alborz'), ('MAZ', 'Mazandaran'), ('GOL', 'Golestan'), ('NKH', 'North Khorasan'), ('KHU', 'Khuzestan'), ('CHB', 'Chaharmahal and Bakhtiari'), ('KHB', 'Kohgiluyeh and Boyer-Ahmad'), ('ISF', 'Isfahan'), ('SEM', 'Semnan'), ('RKH', 'Razavi Khorasan'), ('YZD', 'Yazd'), ('SKH', 'South Khorasan'), ('BSR', 'Bushehr'), ('FAR', 'Fars'), ('KRM', 'Kerman'), ('SIB', 'Sistan and Baluchestan'), ('HOR', 'Hormozga')], max_length=3, verbose_name='Province')),
                ('zip', models.CharField(max_length=10, verbose_name='Zip Code')),
                ('phone', models.CharField(max_length=8, verbose_name='Residential Phone Number')),
            ],
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.iranaddressmodel'),
        ),
    ]
