# Generated by Django 5.2.1 on 2025-07-03 09:19

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profilemodel_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='profile_menu',
            field=models.JSONField(blank=True, default=accounts.models.ProfileModel.default_profile_menu),
        ),
    ]
