# Generated by Django 6.0.2 on 2026-02-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_address_options_address_store_and_more'),
        ('products', '0011_alter_store_name_alter_store_tel_channel'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='address',
            name='active_address_only_for_profiles',
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.CheckConstraint(condition=models.Q(('profile__isnull', False), ('shipping_is_active', False), _connector='OR'), name='active_address_only_for_profiles'),
        ),
        migrations.AlterConstraint(
            model_name='address',
            name='address_owner_check',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('profile__isnull', False), ('store__isnull', True)), models.Q(('profile__isnull', True), ('store__isnull', False)), _connector='OR'), name='address_owner_check'),
        ),
    ]
