# Generated by Django 4.2.14 on 2024-08-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_iranaddressmodel_profilemodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iranaddressmodel',
            name='province',
            field=models.CharField(choices=[('West Azerbaija', 'West Azerbaija'), ('East Azerbaijan', 'East Azerbaijan'), ('Ardabil', 'Ardabil'), ('Kurdistan', 'Kurdistan'), ('Zanjan', 'Zanjan'), ('Gilan', 'Gilan'), ('Kermanshah', 'Kermanshah'), ('Hamadan', 'Hamadan'), ('Qazvin', 'Qazvin'), ('Ilam', 'Ilam'), ('Lorestan', 'Lorestan'), ('Markazi', 'Markazi'), ('Qom', 'Qom'), ('Tehran', 'Tehran'), ('Alborz', 'Alborz'), ('Mazandaran', 'Mazandaran'), ('Golestan', 'Golestan'), ('North Khorasan', 'North Khorasan'), ('Khuzestan', 'Khuzestan'), ('Chaharmahal and Bakhtiari', 'Chaharmahal and Bakhtiari'), ('Kohgiluyeh and Boyer-Ahmad', 'Kohgiluyeh and Boyer-Ahmad'), ('Isfahan', 'Isfahan'), ('Semnan', 'Semnan'), ('Razavi Khorasan', 'Razavi Khorasan'), ('Yazd', 'Yazd'), ('South Khorasan', 'South Khorasan'), ('Bushehr', 'Bushehr'), ('Fars', 'Fars'), ('Kerman', 'Kerman'), ('Sistan and Baluchestan', 'Sistan and Baluchestan'), ('Hormozgan', 'Hormozgan')], max_length=30, verbose_name='Province'),
        ),
    ]
