# Generated by Django 5.2.1 on 2025-08-03 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profilemodel_profile_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelStauts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=500)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telstatus', to='accounts.profilemodel')),
            ],
        ),
    ]
