# Generated by Django 5.2.1 on 2025-08-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_telstauts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelStauts',
            new_name='TelStatus',
        ),
    ]
