# Generated by Django 5.2.1 on 2025-08-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_telstauts_telstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telstatus',
            name='status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
