# Generated by Django 5.2.1 on 2025-08-03 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_telstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telstatus',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telstatus', to='accounts.profilemodel', unique=True),
        ),
    ]
