# Generated by Django 5.1 on 2024-09-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profilemodel_background_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='Phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='fname',
            field=models.CharField(default='Your First Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='lname',
            field=models.CharField(default='Your Last Name', max_length=150, null=True),
        ),
    ]
