# Generated by Django 5.2.1 on 2025-08-06 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_telstatus_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelStatus',
        ),
    ]
