# Generated by Django 5.1 on 2024-09-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profilemodel_phone_alter_profilemodel_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(default='registration/user_avatars/default-avatar.svg', upload_to='registration/user_avatars'),
        ),
    ]
