# Generated by Django 5.1 on 2024-09-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_profilemodel_avatar_alter_profilemodel_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='about_me',
            field=models.TextField(blank=True, default='Describe yourself, your capabilities and talents here. Let others know how awesome you are ;)', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='instagram',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='tweeter',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='Phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='fname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='lname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
