# Generated by Django 5.2.1 on 2025-08-07 13:47

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_profilemodel_tel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='tel_id',
            field=models.CharField(blank=True, default='100000000', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(9)]),
        ),
    ]
