# Generated by Django 5.2.1 on 2025-09-04 20:01

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_profilemodel_tel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='Phone',
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='instagram',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Instagram ID'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='tel_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='telegram',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='tweeter',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Tweeter ID'),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone Number'),
        ),
    ]
