# Generated by Django 5.1 on 2024-09-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_profilemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='Phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='about_me',
            field=models.TextField(blank=True, default='Describe yourself, your capabilities and talents here. Let others know how awesome you are ;)', max_length=1000, null=True, verbose_name='About Me'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='background_pic',
            field=models.ImageField(default='registration/user_headers/default_header.avif', upload_to='registration/user_headers', verbose_name='Header Image'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='fname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='instagram',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Instagram ID'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='lname',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='tweeter',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Tweeter ID'),
        ),
    ]
