# Generated by Django 5.1 on 2024-09-25 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_profilemodel_phone_alter_profilemodel_about_me_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_line1', models.CharField(max_length=300, verbose_name='Address Line 1')),
                ('shipping_line2', models.CharField(max_length=300, verbose_name='Address Line 2')),
                ('shipping_city', models.CharField(max_length=10, verbose_name='City')),
                ('shipping_province', models.CharField(max_length=30, verbose_name='Province')),
                ('shipping_zip', models.CharField(max_length=10, verbose_name='Zip Code')),
                ('shipping_home_phone', models.CharField(max_length=8, verbose_name='Residential Phone Number')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profilemodel', verbose_name='User Profile')),
            ],
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.shippingaddressmodel'),
        ),
        migrations.DeleteModel(
            name='IranAddressModel',
        ),
    ]
