# Generated by Django 5.1 on 2024-09-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_shippingaddressmodel_alter_profilemodel_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddressmodel',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='shippingaddressmodel',
            name='shipping_home_phone',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Residential Phone Number'),
        ),
        migrations.AlterField(
            model_name='shippingaddressmodel',
            name='shipping_line1',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='shippingaddressmodel',
            name='shipping_line2',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='shippingaddressmodel',
            name='shipping_province',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='shippingaddressmodel',
            name='shipping_zip',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip Code'),
        ),
    ]
