# Generated by Django 5.1 on 2024-09-26 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_profilemodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddressmodel',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profilemodel', verbose_name='User Profile'),
        ),
    ]
