# Generated by Django 5.1 on 2024-09-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_shippingaddressmodel_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddressmodel',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='shippingaddressmodel',
            name='shipping_line1',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='shippingaddressmodel',
            name='shipping_line2',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Address Line 2'),
        ),
    ]
