# Generated by Django 4.2.14 on 2024-11-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_shippingaddressmodel_shipping_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='telegram',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Telegram ID'),
        ),
    ]
