# Generated by Django 5.1.3 on 2024-12-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_profilemodel_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
