# Generated by Django 5.1.3 on 2024-12-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_profilemodel_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='instagram',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Instagram ID'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='telegram',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='tweeter',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Tweeter ID'),
        ),
    ]
