# Generated by Django 5.1.3 on 2025-01-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_profilemodel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='telid',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
