# Generated by Django 5.1.3 on 2025-01-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_rename_telid_profilemodel_tel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_level',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='user_level',
            field=models.CharField(choices=[('blue', 'Blue User'), ('green', 'Green User'), ('silver', 'Silver User'), ('gold', 'Golden User')], default='blue', max_length=10),
        ),
    ]
