# Generated by Django 5.1.3 on 2025-01-19 06:37

import accounts.models
import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_remove_user_user_level_profilemodel_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='tel_menu',
            field=models.JSONField(blank=True, default=accounts.models.ProfileModel.default_tel_menu),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='tel_id',
            field=models.CharField(blank=True, default='100000000', max_length=9, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(9)]),
        ),
    ]
