# Generated by Django 5.1.3 on 2025-01-19 08:50

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_profilemodel_tel_menu_alter_profilemodel_tel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='tel_id',
            field=models.CharField(blank=True, default='100000000', max_length=9, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(9)]),
        ),
    ]
