# Generated by Django 5.1.3 on 2025-01-19 12:25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_profilemodel_tel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='extra_button_menu',
            field=models.JSONField(blank=True, default=accounts.models.ProfileModel.default_extra_button_menu),
        ),
    ]
