# Generated by Django 5.1.3 on 2025-01-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_profilemodel_extra_button_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='seller_mode',
            field=models.BooleanField(default=False),
        ),
    ]
