# Generated by Django 5.1.3 on 2024-12-15 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_profilemodel_credit'),
        ('telbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telbotid',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='telbotid',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profilemodel'),
        ),
    ]
