# Generated by Django 5.1.1 on 2025-12-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedmedia',
            name='channel_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cachedmedia',
            name='media_type',
            field=models.CharField(choices=[('video', 'video'), ('photo', 'photo'), ('document', 'document')], default='video', max_length=20),
        ),
        migrations.AlterField(
            model_name='cachedmedia',
            name='channel_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cachedmedia',
            name='file_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='cachedmedia',
            name='video_path',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
