# Generated by Django 5.1.1 on 2025-12-12 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('telbot', '0002_cachedmedia_channel_id_cachedmedia_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedmedia',
            name='product',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cachedmedia', to='accounts.profilemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cachedmedia',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
