# Generated by Django 5.1.1 on 2025-12-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telbot', '0003_cachedmedia_product_cachedmedia_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cachedmedia',
            old_name='product',
            new_name='profile',
        ),
    ]
