# Generated by Django 5.1.1 on 2025-12-12 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telbot', '0004_rename_product_cachedmedia_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cachedmedia',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='cachedmedia',
            name='status',
        ),
    ]
