# Generated by Django 5.1.3 on 2024-12-25 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telbot', '0004_conversation_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conversation',
            new_name='ConversationModel',
        ),
        migrations.RenameModel(
            old_name='Message',
            new_name='MessageModel',
        ),
    ]
