# Generated by Django 5.1.3 on 2025-01-16 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telbot', '0005_rename_conversation_conversationmodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='telbotid',
        ),
    ]
