# Generated by Django 4.2.14 on 2024-10-05 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(unique=True)),
                ('status', models.BooleanField(default=True, verbose_name='Publish Status')),
                ('position', models.IntegerField(verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='TutorialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('video', models.FileField(upload_to='tutorial_videos/', verbose_name='Video')),
                ('video_poster', models.ImageField(upload_to='tutorial_posters/', verbose_name='Video Poster')),
                ('poster', models.ImageField(upload_to='tutorial_poster/', verbose_name='Tutorial Poster')),
                ('about', models.TextField(max_length=5000, verbose_name='Description')),
                ('status', models.BooleanField(default=False, verbose_name='Publish Status')),
                ('slug', models.SlugField(unique=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tutorial_attachments/', verbose_name='Attachments')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorials_authored', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.categorymodel', verbose_name='Tag')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorials_taught', to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Tutorial',
                'verbose_name_plural': 'Toturials',
                'ordering': ['created'],
            },
        ),
    ]
