# Generated by Django 5.2.1 on 2025-08-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='tel_channel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telegram channel ID'),
        ),
        migrations.AddField(
            model_name='store',
            name='tel_group',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telegram group ID'),
        ),
    ]
