# Generated by Django 5.1.1 on 2025-11-08 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialmodel',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tutorialmodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tutorialmodel',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='ArticleModel',
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
        migrations.DeleteModel(
            name='TutorialModel',
        ),
    ]
