# Generated by Django 5.2.6 on 2025-09-22 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='stores',
        ),
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.store', verbose_name='Store'),
            preserve_default=False,
        ),
    ]
