# Generated by Django 5.2.6 on 2025-10-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_min_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=100, unique=True, verbose_name='SKU Code'),
        ),
    ]
