# Generated by Django 5.1.1 on 2025-11-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_tutorialmodel_tag_remove_tutorialmodel_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='markant_id',
            field=models.CharField(default='default', max_length=36, unique=True, verbose_name='Markant ID'),
            preserve_default=False,
        ),
    ]
