# Generated by Django 4.2.14 on 2024-10-05 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_tutorialmodel_installment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
                ('poster', models.ImageField(upload_to='article_poster/', verbose_name='Artilce Poster')),
                ('context', models.TextField(max_length=5000, verbose_name='Description')),
                ('status', models.BooleanField(default=False, verbose_name='Publish Status')),
                ('slug', models.SlugField(unique=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tutorial_attachments/', verbose_name='Attachments')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('time_takes', models.IntegerField(verbose_name='Time it takes to read it')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_authored', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.categorymodel', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['created'],
            },
        ),
    ]
