# Generated by Django 5.2.6 on 2025-09-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_category_stores_category_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='position',
            field=models.IntegerField(default=1, verbose_name='Position'),
        ),
    ]
