# Generated by Django 4.2.14 on 2024-12-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_articlemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.IntegerField()),
                ('length', models.DecimalField(decimal_places=1, max_digits=3)),
                ('stock', models.BooleanField(default=True)),
                ('pic1', models.ImageField(upload_to='shoes_image')),
                ('pic2', models.ImageField(upload_to='shoes_image')),
                ('pic3', models.ImageField(upload_to='shoes_image')),
                ('pic4', models.ImageField(upload_to='shoes_image')),
            ],
        ),
    ]
