# Generated by Django 5.1.3 on 2024-12-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_shoemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoemodel',
            name='code',
            field=models.CharField(default='001010101', max_length=9),
        ),
        migrations.AddField(
            model_name='shoemodel',
            name='off',
            field=models.IntegerField(default=0),
        ),
    ]
