# Generated by Django 5.2.6 on 2025-09-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='tel_channel',
            field=models.CharField(blank=True, default='@', max_length=20, null=True, verbose_name='Telegram channel ID'),
        ),
        migrations.AlterField(
            model_name='store',
            name='tel_group',
            field=models.CharField(blank=True, default='@', max_length=20, null=True, verbose_name='Telegram group ID'),
        ),
    ]
