# Generated by Django 5.1.1 on 2025-12-24 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_store_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='city',
        ),
        migrations.RemoveField(
            model_name='store',
            name='province',
        ),
    ]
