# Generated by Django 5.2.11 on 2026-05-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
    ]
