# Generated by Django 5.2.6 on 2025-09-22 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profilemodel_server_store'),
        ('products', '0005_alter_store_tel_channel_alter_store_tel_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='profile',
        ),
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_store', to='accounts.profilemodel', verbose_name='Owner Profile'),
            preserve_default=False,
        ),
    ]
