# Generated by Django 5.1.1 on 2025-12-24 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_store_city_remove_store_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='address',
        ),
    ]
