# Generated by Django 5.2.11 on 2026-06-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
