# Generated by Django 5.1.1 on 2026-01-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_store_banner_image_store_company_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='intro_video',
            field=models.FileField(blank=True, null=True, upload_to='store_intro_videos/'),
        ),
    ]
