# Generated by Django 5.1.1 on 2026-01-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_store_intro_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='markant_id',
            field=models.CharField(max_length=36, verbose_name='Markant ID'),
        ),
    ]
