# Generated by Django 6.0.2 on 2026-02-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_store_markant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Store Name'),
        ),
        migrations.AlterField(
            model_name='store',
            name='tel_channel',
            field=models.CharField(blank=True, default='@', max_length=20, null=True, unique=True, verbose_name='Telegram channel ID'),
        ),
    ]
