# Generated by Django 5.1.3 on 2025-01-22 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(default=1234567899, on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='products.product', verbose_name='Product'),
            preserve_default=False,
        ),
    ]
