# Generated by Django 5.1.3 on 2025-01-29 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_profilemodel_settings_menu'),
        ('products', '0014_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profilemodel', to='accounts.profilemodel'),
            preserve_default=False,
        ),
    ]
