# Generated by Django 5.1.3 on 2025-02-10 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_profilemodel_settings_menu'),
        ('products', '0016_remove_product_is_available_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='user',
        ),
        migrations.AddField(
            model_name='store',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='accounts.profilemodel'),
            preserve_default=False,
        ),
    ]
